name: .NET API Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build 'BlazorSchoolApi' --configuration Release

      - name: Test
        run:  dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover      
    