name: .NET API Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build 'BlazorSchoolApi' --configuration Release

      - name: Publish
        run: dotnet publish 'BlazorSchoolApi' -c Release -o publish_output

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: site1522.siteasp.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: publish_output/
          server-dir: wwwroot/